In [1]:
import numpy as np

Create a 1D array of numbers from 0 to 9

In [3]:
x=np.arange(0,10,1)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Create a 3×3 numpy array of all True’s

In [8]:
y=np.ones((3,3), dtype='bool')
y

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Given an array as input, print only odd numbers as output

In [24]:
x=np.array([3,5,6,1,4,7])
x

array([3, 5, 6, 1, 4, 7])

In [25]:
for i in x:
 if i%2!=0:
    print (i)

3
5
1
7


Replace all odd numbers in arr with -2

In [29]:
for n, i in enumerate(x):
 if i%2!=0:
    x[n]=-2

In [30]:
x

array([-2, -2,  6, -2,  4, -2])

How to reshape an array?

In [32]:
x.reshape(6,1)

array([[-2],
       [-2],
       [ 6],
       [-2],
       [ 4],
       [-2]])

Convert a 1D array to a 2D array with 2 rows

In [36]:
y=np.array([3,5,6,1])
y

array([3, 5, 6, 1])

In [37]:
y.reshape(2,2)

array([[3, 5],
       [6, 1]])

In [40]:
a=np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Given an array  a  = [1,2,3,4,5,6,7,8,9] , create  new array b from a such that b includes all odd numbers and 4 multiples.

In [48]:
b=np.zeros(shape=(1,6))
b

array([[0., 0., 0., 0., 0., 0.]])

In [51]:
for n,i in enumerate(a):
    if i%2!=0 & i%4==0:
        b[n]=x[n]
        

IndexError: index 2 is out of bounds for axis 0 with size 1

Given array, check if there are any null values and print them out. 

In [56]:
s=np.array([1,2,3,np.nan,4,5,np.nan])
s

array([ 1.,  2.,  3., nan,  4.,  5., nan])

In [65]:
t=np.isnan(s)
t

array([False, False, False,  True, False, False,  True])

How to replace all missing values with 0 in a numpy array?

In [70]:
for n,i in enumerate(t):
    if i=="True":
        np.replace.s[n]=0

In [71]:
s

array([ 1.,  2.,  3., nan,  4.,  5., nan])

How to find the count of each unique number in a NumPy array?

In [76]:
a=np.array(['cat','bat', 'ball','fall', 'cat', 'bat', 'bat','bat','fall','mall'])

In [86]:
np.unique(a)

array(['ball', 'bat', 'cat', 'fall', 'mall'], dtype='<U4')

In [87]:
np.unique(a, return_counts='True')

(array(['ball', 'bat', 'cat', 'fall', 'mall'], dtype='<U4'),
 array([1, 4, 2, 2, 1]))

How to convert a numeric to a categorical (text) array

In [88]:
num=np.array([1,2,3])

In [90]:
def num_to_str(x):
    if x==1:
        retun 'True'
        if x==2:
            return 'False'
        if x==3:
            return 'neutral'

SyntaxError: invalid syntax (<ipython-input-90-ea4ae190b7e8>, line 3)

Write a program to print all numbers between 99 and 299 which are either divisible by 5 or 7. Exclude the elements which are divisible by both. 

In [100]:
x=np.arange(99,300)
x

array([ 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
       112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124,
       125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137,
       138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150,
       151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163,
       164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176,
       177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189,
       190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202,
       203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215,
       216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228,
       229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241,
       242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254,
       255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267,
       268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 27

In [102]:
for i in x:
    if i%5==0 or i%7==0:
        print(i)

100
105
110
112
115
119
120
125
126
130
133
135
140
145
147
150
154
155
160
161
165
168
170
175
180
182
185
189
190
195
196
200
203
205
210
215
217
220
224
225
230
231
235
238
240
245
250
252
255
259
260
265
266
270
273
275
280
285
287
290
294
295


Write a program to reverse an array and print

In [107]:
len(x)

201

In [116]:
x[:-1]

array([ 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
       112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124,
       125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137,
       138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150,
       151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163,
       164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176,
       177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189,
       190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202,
       203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215,
       216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228,
       229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241,
       242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254,
       255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267,
       268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 27

In [122]:
y=np.empty(shape=(1,200))

In [125]:
for i in x:
    j=200
    y[j]=x[i]
    j=j-1

IndexError: index 200 is out of bounds for axis 0 with size 1

Tired attempting quest 7,9,11, 13... unable to think ofany other possible ways